### ISSUE TITLE
URL Validation - Frontend

### ISSUE THREAD

**Issue by anonymous-sidhax** [Collaborative-Open-Source-Projects/shrinkurlnow#37]
There is no error message being displayed on frontend for invalid URLs, can you please handle such cases?
![image](https://github.com/user-attachments/assets/a5e90b63-d9ba-4b8e-88d2-c1971f9656e3)

**Comment by ketansahugit** [comment]
Is there any guide on how to set up this project?

**Comment by shreejeshballal** [comment]
> Is there any guide on how to set up this project?

you can check the info channel in discord, and also for initial setup you can use the read me

**Comment by anonymous-sidhax** [comment]
Also please add a close button or something to close this alert/dialog box

![image](https://github.com/user-attachments/assets/015d2e1a-f886-4c66-9b78-c397789f755b)
